<?php
/**
 * =============================================================================
 * MC 28 - General Ledger (GL) Mapping Configuration
 * =============================================================================
 * @package     Pusat Riyal
 * @version     1.0.0
 * @author      Denmas Totok (Generated by Gemini)
 * * Purpose:
 * - Mengatur "Posting Profile" agar script tidak hardcoded.
 * - User memilih akun mana yang dipakai untuk Penjualan, Persediaan, HPP, dll.
 * =============================================================================
 */

defined('ABSPATH') || exit;

// 1. REGISTRASI MENU (Di Bawah Menu MASTER / Admin Hub)
/*
add_action('admin_menu', function() {
    add_submenu_page(
        'puri-master',         // Parent: Master Data
        'Pengaturan Akun GL',  // Page Title
        '⚙️ GL Mapping',       // Menu Title
        'manage_options',
        'puri-gl-mapping',
        'puri_render_gl_mapping_page'
    );
});
*/

// 2. HELPER FUNCTION (GLOBAL)
// Fungsi ini yang akan dipanggil oleh modul POS, Adjustment, dll.
// Contoh: puri_gl('sales_cash') -> Returns '4110'
if (!function_exists('puri_gl')) {
    function puri_gl($key) {
        $map = get_option('puri_gl_settings', []);
        
        // Default Fallback (Jika setting belum disimpan)
        $defaults = [
            'sales_cash'    => '4110', // Penjualan Tunai
            'inventory'     => '1310', // Persediaan Barang
            'cogs'          => '5110', // HPP
            'cash_drawer'   => '1111', // Kas Laci
            'suspense'      => '1999', // Selisih Sementara
            'ar_trade'      => '1210', // Piutang Usaha
            'ap_trade'      => '2110', // Hutang Usaha
            'equity'        => '3110', // Modal
        ];

        return isset($map[$key]) && !empty($map[$key]) ? $map[$key] : ($defaults[$key] ?? '0000');
    }
}

// 3. HANDLER SIMPAN
add_action('admin_post_puri_save_gl_map', function() {
    if (!current_user_can('manage_options')) wp_die('Unauthorized');
    check_admin_referer('puri_save_gl_map', 'puri_nonce');

    $data = [];
    foreach($_POST['map'] as $key => $val) {
        $data[$key] = sanitize_text_field($val);
    }
    
    update_option('puri_gl_settings', $data);
    wp_redirect(admin_url('admin.php?page=puri-gl-mapping&msg=updated'));
    exit;
});

// 4. RENDER HALAMAN SETTING
function puri_render_gl_mapping_page() {
    global $wpdb;
    
    // Ambil Data Akun untuk Dropdown
    $charts = $wpdb->get_results("SELECT code, name, type FROM " . puri_table_name('T_CHART') . " ORDER BY code ASC");
    
    // Ambil Settingan Tersimpan
    $current = get_option('puri_gl_settings', []);

    // Helper Dropdown
    $render_select = function($key, $label, $filter_type = '') use ($charts, $current) {
        $val = $current[$key] ?? '';
        echo "<tr><th><label>$label</label></th><td>";
        echo "<select name='map[$key]' class='puri-select2' style='width:100%'>";
        echo "<option value=''>-- Pilih Akun --</option>";
        foreach ($charts as $c) {
            // Filter Opsional (Misal hanya tampilkan ASSET)
            // if($filter_type && $c->type !== $filter_type) continue;
            
            $selected = selected($val, $c->code, false);
            echo "<option value='{$c->code}' $selected>{$c->code} - {$c->name} ({$c->type})</option>";
        }
        echo "</select></td></tr>";
    };

    ?>
    <div class="wrap">
        <h1>⚙️ General Ledger (GL) Mapping</h1>
        <p>Tentukan akun referensi untuk otomatisasi jurnal. Perubahan di sini akan mempengaruhi modul POS dan Stok.</p>
        
        <?php if(isset($_GET['msg'])): ?>
            <div class="notice notice-success is-dismissible"><p>✅ Pengaturan berhasil disimpan.</p></div>
        <?php endif; ?>

        <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>">
            <input type="hidden" name="action" value="puri_save_gl_map">
            <?php wp_nonce_field('puri_save_gl_map', 'puri_nonce'); ?>

            <div style="display:flex; gap:20px; flex-wrap:wrap;">
                
                <div class="card" style="flex:1; min-width:300px; padding:15px;">
                    <h3>💰 Penjualan & Kas (POS)</h3>
                    <table class="form-table">
                        <?php 
                        $render_select('cash_drawer', 'Kas Laci Utama (POS)');
                        $render_select('sales_cash', 'Akun Penjualan Tunai');
                        $render_select('ar_trade', 'Akun Piutang (Receivable)');
                        ?>
                    </table>
                </div>

                <div class="card" style="flex:1; min-width:300px; padding:15px;">
                    <h3>📦 Persediaan & HPP</h3>
                    <table class="form-table">
                        <?php 
                        $render_select('inventory', 'Akun Persediaan Barang');
                        $render_select('cogs', 'Akun HPP (Cost of Goods Sold)');
                        $render_select('suspense', 'Akun Selisih Opname (Adjustment)');
                        ?>
                    </table>
                </div>

                <div class="card" style="flex:1; min-width:300px; padding:15px;">
                    <h3>🚚 Pembelian / Procurement</h3>
                    <table class="form-table">
                        <?php 
                        $render_select('ap_trade', 'Akun Hutang Usaha (Payable)');
                        // Tambahan jika perlu
                        ?>
                    </table>
                </div>
            </div>

            <hr>
            <button type="submit" class="button button-primary button-large">Simpan Konfigurasi</button>
        </form>
    </div>

    <script>
        jQuery(document).ready(function($) {
            $('.puri-select2').select2();
        });
    </script>
    <?php
}