<?php
/**
 * MC 27 - General Journal Entry (Jurnal Umum Manual)
 * Version: 1.0.0
 * Author: Denmas Totok (Generated by Gemini)
 *
 * Purpose:
 * - Form input jurnal manual (Multi-line).
 * - Digunakan untuk: Jurnal Balik, Koreksi, Depresiasi, dan Non-Cash Transaction.
 * - Melengkapi siklus "Stock Opname" (Tahap Investigasi/Reversal).
 *
 * Logic:
 * - User input Header (Tanggal, Ref Manual/Auto, Deskripsi).
 * - User input Rows (Akun, Debit, Kredit).
 * - Validasi: Total Debit HARUS SAMA DENGAN Total Kredit (Balance).
 * - Posting menggunakan engine core.
 */

defined('ABSPATH') || exit;

add_action('admin_menu', function() {
    add_submenu_page(
        'puri-keuangan',        // Parent: Keuangan (Sesuaikan dengan MC-00)
        'Jurnal Umum',          // Page Title
        '📒 Jurnal Umum',       // Menu Title
        'manage_options',       // Capability (Hanya Admin/Finance)
        'puri-manual-journal',  // Slug
        'puri_render_manual_journal_page'
    );
});

add_action('admin_post_puri_submit_manual_journal', 'puri_handle_manual_journal_submit');

function puri_render_manual_journal_page() {
    puri_check_cap('manage_options');
    
    global $wpdb;
    
    // Ambil semua akun CoA untuk dropdown
    $accounts = $wpdb->get_results("SELECT code, name, type FROM " . puri_table_name('T_CHART') . " ORDER BY code ASC");
    $accounts_json = json_encode($accounts); // Untuk JS

    ?>
    <div class="wrap">
        <h1>📒 Input Jurnal Umum (General Entry)</h1>
        
        <?php if (isset($_GET['msg'])): ?>
            <div class="notice notice-success is-dismissible"><p>✅ <?php echo esc_html(urldecode($_GET['msg'])); ?></p></div>
        <?php endif; ?>
        <?php if (isset($_GET['err'])): ?>
            <div class="notice notice-error is-dismissible"><p>❌ <?php echo esc_html(urldecode($_GET['err'])); ?></p></div>
        <?php endif; ?>

        <form method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>" id="journal_form">
            <input type="hidden" name="action" value="puri_submit_manual_journal">
            <?php wp_nonce_field('puri_journal_action', 'puri_journal_nonce'); ?>

            <div class="card" style="padding:15px; margin-top:20px; max-width:100%;">
                <table class="form-table" style="margin:0;">
                    <tr>
                        <th style="width:150px;">Tanggal Transaksi</th>
                        <td><input type="date" name="trx_date" value="<?php echo date('Y-m-d'); ?>" required></td>
                        
                        <th style="width:150px;">No. Referensi</th>
                        <td>
                            <input type="text" name="ref_manual" placeholder="Auto (JU-xxx)" class="regular-text">
                            <p class="description">Kosongkan untuk generate otomatis.</p>
                        </td>
                    </tr>
                    <tr>
                        <th>Deskripsi / Memo</th>
                        <td colspan="3">
                            <input type="text" name="description" class="large-text" required placeholder="Contoh: Pembalikan selisih opname tgl 9 Jan">
                        </td>
                    </tr>
                </table>
            </div>

            <div class="card" style="padding:0; margin-top:20px;">
                <table class="wp-list-table widefat fixed striped" id="journal_table">
                    <thead>
                        <tr>
                            <th style="width:40%;">Akun GL</th>
                            <th style="width:25%; text-align:right;">Debit (Rp)</th>
                            <th style="width:25%; text-align:right;">Kredit (Rp)</th>
                            <th style="width:10%; text-align:center;">#</th>
                        </tr>
                    </thead>
                    <tbody id="journal_body">
                        </tbody>
                    <tfoot>
                        <tr style="background:#f0f0f1; font-weight:bold;">
                            <td style="text-align:right;">TOTAL</td>
                            <td style="text-align:right;" id="total_debit">0</td>
                            <td style="text-align:right;" id="total_credit">0</td>
                            <td style="text-align:center;" id="balance_status">Checking...</td>
                        </tr>
                    </tfoot>
                </table>
                
                <div style="padding:10px; background:#fff; border-top:1px solid #ddd;">
                    <button type="button" class="button" id="btn_add_row">+ Tambah Baris</button>
                </div>
            </div>

            <div style="margin-top:20px;">
                <button type="submit" class="button button-primary button-large" id="btn_submit" disabled>POSTING JURNAL</button>
            </div>
        </form>
    </div>

    <script>
    jQuery(document).ready(function($) {
        const accounts = <?php echo $accounts_json; ?>;
        
        function formatRupiah(num) {
            return new Intl.NumberFormat('id-ID').format(num);
        }

        function addRow() {
            let options = '<option value="">-- Pilih Akun --</option>';
            accounts.forEach(acc => {
                options += `<option value="${acc.code}">${acc.code} - ${acc.name}</option>`;
            });

            let row = `
                <tr>
                    <td>
                        <select name="items[][account]" class="puri-select2" style="width:100%" required>
                            ${options}
                        </select>
                    </td>
                    <td><input type="number" name="items[][debit]" class="input-money inp-debit" value="0" style="width:100%; text-align:right;"></td>
                    <td><input type="number" name="items[][credit]" class="input-money inp-credit" value="0" style="width:100%; text-align:right;"></td>
                    <td style="text-align:center;"><button type="button" class="button btn-remove"><span class="dashicons dashicons-trash" style="margin-top:4px;"></span></button></td>
                </tr>
            `;
            $('#journal_body').append(row);
            $('.puri-select2').select2(); // Re-init Select2
            calcTotal();
        }

        // Event Delegation
        $(document).on('click', '.btn-remove', function() {
            $(this).closest('tr').remove();
            calcTotal();
        });

        $(document).on('keyup change', '.input-money', function() {
            calcTotal();
        });

        $('#btn_add_row').click(function() {
            addRow();
        });

        function calcTotal() {
            let sumDr = 0;
            let sumCr = 0;

            $('.inp-debit').each(function() { sumDr += parseFloat($(this).val()) || 0; });
            $('.inp-credit').each(function() { sumCr += parseFloat($(this).val()) || 0; });

            $('#total_debit').text(formatRupiah(sumDr));
            $('#total_credit').text(formatRupiah(sumCr));

            let diff = Math.abs(sumDr - sumCr);
            let btn = $('#btn_submit');
            let stat = $('#balance_status');

            if (sumDr > 0 && sumCr > 0 && diff < 1) { // Toleransi koma kecil
                stat.html('<span style="color:green;">BALANCE</span>');
                btn.prop('disabled', false);
            } else {
                stat.html('<span style="color:red;">NOT BALANCE</span>');
                btn.prop('disabled', true);
            }
        }

        // Init minimal 2 rows
        addRow();
        addRow();
    });
    </script>
    <?php
}

function puri_handle_manual_journal_submit() {
    puri_check_cap('manage_options');
    check_admin_referer('puri_journal_action', 'puri_journal_nonce');

    global $wpdb;
    $engine = puri_engine(); // Asumsi engine sudah diload

    $trx_date = sanitize_text_field($_POST['trx_date']);
    $desc = sanitize_text_field($_POST['description']);
    $ref_id = sanitize_text_field($_POST['ref_manual']);
    
    if (empty($ref_id)) {
        $ref_id = 'JU-' . date('ymdHi') . rand(100, 999);
    }

    $items_raw = $_POST['items'];
    $items_clean = [];
    $total_dr = 0;
    $total_cr = 0;

    // 1. Validasi & Sanitasi Data
    foreach($items_raw as $row) {
        $acc = sanitize_text_field($row['account']);
        $dr = floatval($row['debit']);
        $cr = floatval($row['credit']);

        if (empty($acc)) continue; // Skip baris kosong
        if ($dr == 0 && $cr == 0) continue; // Skip baris 0

        $total_dr += $dr;
        $total_cr += $cr;
        
        $items_clean[] = ['acc'=>$acc, 'dr'=>$dr, 'cr'=>$cr];
    }

    // 2. Cek Balance (Server Side)
    if (abs($total_dr - $total_cr) > 1) {
        wp_redirect(admin_url('admin.php?page=puri-manual-journal&err='.urlencode('Jurnal tidak balance! Cek kembali inputan.')));
        exit;
    }

    if (empty($items_clean)) {
        wp_redirect(admin_url('admin.php?page=puri-manual-journal&err='.urlencode('Data kosong.')));
        exit;
    }

    // 3. Posting
    $wpdb->query('START TRANSACTION');
    try {
        foreach($items_clean as $line) {
            // Gunakan engine post_journal untuk setiap baris
            // Engine biasanya insert satu baris T_JOURNAL per call
            $res = $engine->post_journal(
                $ref_id,
                $line['acc'],
                $line['dr'],
                $line['cr'],
                $desc . " (" . $line['acc'] . ")" // Desc detail
            );
            
            if (is_wp_error($res)) {
                throw new Exception($res->get_error_message());
            }
        }

        $wpdb->query('COMMIT');
        wp_redirect(admin_url('admin.php?page=puri-manual-journal&msg='.urlencode("Jurnal Berhasil Diposting! Ref: $ref_id")));
        exit;

    } catch (Exception $e) {
        $wpdb->query('ROLLBACK');
        wp_redirect(admin_url('admin.php?page=puri-manual-journal&err='.urlencode('Gagal: ' . $e->getMessage())));
        exit;
    }
}